apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gitlab-backup
