apiVersion: v1
kind: Pod
metadata:
  name: backup-reader
  namespace: rds-git
spec:
  containers:
  - name: backup-reader
    image: alpine
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /mnt/backup
      name: backup-volume
  volumes:
  - name: backup-volume
    persistentVolumeClaim:
      claimName: gitlab-backup-pvc
