apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-backup-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/opt/gitlab/backups"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
