apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-backup-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /var/opt/gitlab/backups
