apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-reader
  namespace: git-rds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-reader
  template:
    metadata:
      labels:
        app: backup-reader
    spec:
      containers:
        - name: backup-reader
          image: busybox
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: backup-volume
              mountPath: /mnt/backup
      volumes:
        - name: backup-volume
          persistentVolumeClaim:
            claimName: gitlab-backup-pvc
