apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitlab-backup
  namespace: rds-git
spec:
  schedule: "0 1 * * *"  # Every day at 1 AM
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gitlab-backup-sa
          containers:
            - name: backup-runner
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  POD=$(kubectl get pod -n rds-git -l app=gitlab -o jsonpath="{.items[0].metadata.name}")
                  kubectl exec -n rds-git $POD -- gitlab-rake gitlab:backup:create
          restartPolicy: OnFailure
