apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  DATABASE_URL: "postgresql://{{ .Values.global.psql.username }}:${POSTGRES_PASSWORD}@{{ .Values.global.psql.host }}:{{ .Values.global.psql.port }}/{{ .Values.global.psql.database }}?sslmode={{ .Values.global.psql.sslmode }}"
  GITLAB_DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
  GITLAB_DATABASE_USERNAME: "{{ .Values.global.psql.username }}"
  GITLAB_DATABASE_HOST: "{{ .Values.global.psql.host }}"
  GITLAB_DATABASE_PORT: "{{ .Values.global.psql.port }}"
  GITLAB_DATABASE_NAME: "{{ .Values.global.psql.database }}"
  GITLAB_DATABASE_SSL: "true"
  GITLAB_HOST: "{{ .Values.ingress.hosts[0].host }}"
  GITLAB_PORT: "80"
  GITLAB_HTTPS: "{{ .Values.global.hosts.https | default "false" }}"
  GITLAB_RELATIVE_URL_ROOT: ""
  GITLAB_EMAIL_FROM: "gitlab@{{ .Values.ingress.hosts[0].host }}"
  GITLAB_EMAIL_DISPLAY_NAME: "GitLab"
  GITLAB_EMAIL_REPLY_TO: "noreply@{{ .Values.ingress.hosts[0].host }}"
  GITLAB_SECRETS_DB_KEY_BASE: "${DB_KEY_BASE}"
  GITLAB_SECRETS_SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
  GITLAB_SECRETS_OTP_KEY_BASE: "${OTP_KEY_BASE}"
  RAILS_ENV: "production"
  {{- if .Values.global.smtp.enabled }}
  SMTP_ENABLED: "true"
  SMTP_USER: "{{ .Values.global.smtp.user }}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
  SMTP_HOST: "{{ .Values.global.smtp.host }}"
  SMTP_PORT: "{{ .Values.global.smtp.port }}"
  SMTP_DOMAIN: "{{ .Values.global.smtp.domain }}"
  SMTP_AUTHENTICATION: "{{ .Values.global.smtp.authentication }}"
  SMTP_STARTTLS_AUTO: "{{ .Values.global.smtp.starttls_auto }}"
  {{- end }}
