apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug
  namespace: rds-git
spec:
  containers:
  - name: debug-container
    image: busybox
    command: [ "sleep", "3600" ]
    volumeMounts:
    - mountPath: /mnt
      name: pvc
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: gitlab-pvc
