apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitlab-backup
spec:
  schedule: "0 0 * * *"  # Schedule at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: gitlab-backup
              image: gitlab-5dbf5797c9-lttkb  # Replace with your GitLab container image
              command:
                - "/bin/bash"
                - "-c"
                - "gitlab-rake gitlab:backup:create"
              volumeMounts:
                - mountPath: /var/opt/gitlab/backups
                  name: gitlab-backup-volume
          restartPolicy: OnFailure
          volumes:
            - name: gitlab-backup-volume
              persistentVolumeClaim:
                claimName: gitlab-backup-pvc
