apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      securityContext:
        fsGroup: 1000  # Ensure GitLab process can access volumes

      initContainers:
        - name: init
          image: busybox:1.35
          command: ["sh", "-c", "chown -R 1000:1000 /var/opt/gitlab && chmod -R 755 /var/opt/gitlab"]
          volumeMounts:
            - name: gitlab-storage
              mountPath: /var/opt/gitlab

      containers:
        - name: gitlab
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - containerPort: 80
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://{{ first .Values.ingress.hosts }}'
                gitlab_rails['db_host'] = '{{ .Values.database.host }}'
                gitlab_rails['db_port'] = {{ .Values.database.port }}
                gitlab_rails['db_username'] = '{{ .Values.database.user }}'
                gitlab_rails['db_password'] = '{{ .Values.database.password }}'
                gitlab_rails['db_database'] = '{{ .Values.database.dbname }}'
                gitlab_rails['db_adapter'] = 'postgresql'
                gitlab_rails['db_encoding'] = 'unicode'
                gitlab_rails['boot_timeout'] = 1200  # Increased to 20 minutes
                puma['worker_timeout'] = 600
          resources:
            requests:
              memory: "4Gi"  # Increased minimum
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "2"
          #startupProbe:
            #httpGet:
              #path: /-/readiness
              #port: 80
            #failureThreshold: 60  # 60 attempts
            #periodSeconds: 10  # 10 minutes total
          livenessProbe:
            httpGet:
              path: /-/health
              port: 80
            initialDelaySeconds: 600  # Start checking after 10 minutes
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/readiness
              port: 80
            initialDelaySeconds: 300  # Start checking after 5 minutes
            periodSeconds: 10
          volumeMounts:
            - name: gitlab-storage
              mountPath: /var/opt/gitlab
      volumes:
        - name: gitlab-storage
          persistentVolumeClaim:
            claimName: gitlab-pvc
