apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      initContainers:
        - name: volume-permission-fix
          image: busybox:1.35
          command: ["sh", "-c", "chown -R 1000:1000 /var/opt/gitlab && chmod -R 755 /var/opt/gitlab"]
          volumeMounts:
            - name: gitlab-storage
              mountPath: /var/opt/gitlab
      
      containers:
        - name: gitlab
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://{{ first .Values.ingress.hosts }}'
                gitlab_rails['db_host'] = '{{ .Values.database.host }}'
                gitlab_rails['db_port'] = {{ .Values.database.port }}
                gitlab_rails['db_username'] = '{{ .Values.database.user }}'
                gitlab_rails['db_password'] = '{{ .Values.database.password }}'
                gitlab_rails['db_database'] = '{{ .Values.database.dbname }}'
                gitlab_rails['db_adapter'] = 'postgresql'
                gitlab_rails['db_encoding'] = 'unicode'
                gitlab_rails['boot_timeout'] = 600  # Increased timeout
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"
          startupProbe:
            httpGet:
              path: /-/readiness
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /-/health
              port: 80
            initialDelaySeconds: 600  # Increased for slow starts
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/readiness
              port: 80
            initialDelaySeconds: 120  # Increased initial delay
            periodSeconds: 10
            failureThreshold: 12
          volumeMounts:
            - name: gitlab-storage
              mountPath: /var/opt/gitlab
      volumes:
        - name: gitlab-storage
          persistentVolumeClaim:
            claimName: gitlab-pvc
