apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: {{ .Values.env.GITLAB_OMNIBUS_CONFIG | quote }}
