apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
type: Opaque
data:
  postgresql-password: <base64-encoded-postgres-password>
  smtp-password: <base64-encoded-smtp-password>
  gitlab-rails-secret: <base64-encoded-rails-secret>
  gitlab-root-password: <base64-encoded-root-password>
