apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv
spec:
  capacity:
    storage: "{{ .Values.storage.size }}"  # Ensure this is a string in values.yaml
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}  # Ensures correct indentation
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "{{ .Values.storage.storageClassName }}"
  hostPath:
    path: "/mnt/data"
