apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  # Database credentials
  postgres-password: {{ .Values.global.psql.password | b64enc | quote }}
  
  # GitLab secrets
  db-key-base: {{ .Values.global.secrets.dbKeyBase | b64enc | quote }}
  secret-key-base: {{ .Values.global.secrets.secretKeyBase | b64enc | quote }}
  otp-key-base: {{ .Values.global.secrets.otpKeyBase | b64enc | quote }}
  
  # SMTP credentials (if enabled)
  {{- if .Values.global.smtp.enabled }}
  smtp-password: {{ .Values.global.smtp.password | b64enc | quote }}
  {{- end }}
