apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
    release: gitlab
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # NLB for AWS
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-0a589a5ba3261c27a,eipalloc-08d609832118287e2"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: gitlab
    release: gitlab
