apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: gitlab
    release: {{ .Release.Name }}
