apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: workhorse
    port: 8181
    targetPort: 8181
  selector:
    app: {{ .Chart.Name }}
    component: rails

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-sidekiq-service
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - name: sidekiq
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Chart.Name }}
    component: sidekiq
