apiVersion: v2
name: gitlab-external-postgresql
description: GitLab with external PostgreSQL (AWS RDS)
version: 0.1.0
appVersion: 15.0.0
dependencies:
- name: gitlab
  version: "6.9.1"
  repository: "https://charts.gitlab.io"
  condition: gitlab.enabled
