replicaCount: 1

image:
  repository: gitlab/gitlab-ce
  tag: "17.10.1"
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: gitlab.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi

postgresql:
  host: dev-db.cyxw2mqqud77.us-east-1.rds.amazonaws.com
  port: 5432
  database: mydatabase
  username: dbadmin
  existingSecret: gitlab-secret
  secretKey: ChangeMe123!
