image:
  repository: gitlab/gitlab-ce
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: gitlab.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

env:
  GITLAB_OMNIBUS_CONFIG: |
    external_url 'http://gitlab.example.com'
    gitlab_rails['db_adapter'] = 'postgresql'
    gitlab_rails['db_host'] = 'database-1.ca7um2agoffa.us-east-1.rds.amazonaws.com'
    gitlab_rails['db_port'] = 5432
    gitlab_rails['db_username'] = 'gitlab'
    gitlab_rails['db_password'] = 'gitlab1231'
    gitlab_rails['db_database'] = 'database-1'
