replicaCount: 1

image:
  repository: gitlab/gitlab-ce
  tag: "17.7.2-ce.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: gitlab.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi

postgresql:
  enabled: false  # disables inbuilt PostgreSQL
  host: dev-db.cyxw2mqqud77.us-east-1.rds.amazonaws.com
  port: 5432
  database: gitlab        # ✅ recommend using `gitlab` DB (not mydatabase)
  username: gitlab        # ✅ use matching user
  existingSecret: gitlab-secret
  existingSecretPasswordKey: POSTGRES_PASSWORD

env:
  POSTGRES_DB: gitlab
  POSTGRES_USER: gitlab
  POSTGRES_PASSWORD: Muruga@1
  POSTGRES_HOST: dev-db.cyxw2mqqud77.us-east-1.rds.amazonaws.com

resources:
  requests:
    memory: "4Gi"
    cpu: "2"
  limits:
    memory: "6Gi"
    cpu: "3"

