apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-ce
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ .Values.gitlab.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitlab-ce
                port:
                  number: {{ .Values.gitlab.service.port }}
