apiVersion: v1
kind: Service
metadata:
  name: gitlab-ce
spec:
  type: {{ .Values.gitlab.service.type }}
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      port: {{ .Values.gitlab.service.port }}
      targetPort: 80
